# Entwicklung der Menschenrechte weltweit: Veränderungen im Human Rights Index
## Abgabetermin
Datum: **15. Dezember 2025**
## Gruppenmitglieder
### Alessandro Zandt 
E-Mail: zandtale@students.zhaw.ch
### David Hascher
E-Mail: haschdav@students.zhaw.ch
### Tauland Strellci
E-Mail: streltau@students.zhaw.ch
## Kurzer Projektbeschrieb
In diesem Projekt analysieren wir die zeitliche Entwicklung des Human Rights Index für verschiedene Länder.
Der Datensatz Human Rights Index von V-Dem misst, wie stark grundlegende Menschenrechte in einzelnen Ländern geschützt sind. Der Index basiert auf Expertenschätzungen und umfasst zentrale Bereiche wie:

- Schutz vor staatlicher Gewalt (Tortur, politische Morde, Zwangsarbeit)

- Rechte auf Eigentum

- Bewegungsfreiheit

- Religionsfreiheit

- Meinungs- und Pressefreiheit

- Vereinigungsfreiheit

Der Index reicht von 0 bis 1, wobei 1 ein sehr hohes Schutzniveau der Menschenrechte darstellt.


### Datensatz
Quelle: https://ourworldindata.org/vdem-human-rights-data
### Fragestellung
Wie haben sich die Menschenrechte in verschiedenen Ländern in den letzten Jahren entwickelt, und welche drei Staaten verzeichnen die stärksten Verbesserungen bzw. Verschlechterungen im Human Rights Index?

## 1. Daten beschaffen und laden

- Den Datensatz konnten wir in passender Form direkt von der Webseite "OurWorldinData" herunterladen

In [18]:
# Daten geladen
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/human-rights-index-vdem.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/human-rights-index-vdem.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [19]:
df.head()

        Entity Code  Year  civ_libs_vdem__estimate_best owid_region
0  Afghanistan  AFG  1789                         0.121         NaN
1  Afghanistan  AFG  1790                         0.121         NaN
2  Afghanistan  AFG  1791                         0.121         NaN
3  Afghanistan  AFG  1792                         0.121         NaN
4  Afghanistan  AFG  1793                         0.121         NaN

## 2. Daten vorbereiten

- Die Daten wären noch nicht in einem passenden Format. Wir nutzten den df.head()-Befehl um die ersten 5 Zeilen darzustellen. Darauf Basierend fällten wir Entscheidungen über mögliche modifikationen.
- Wir entschieden uns, dass die Spaltennamen auf Deutsch darzustellen und eine ganze Spalte nicht anzeigen zu lassen.

In [17]:
df = pd.read_csv(
    "https://ourworldindata.org/grapher/human-rights-index-vdem.csv?v=1&csvType=full&useColumnShortNames=true"
)

# Spalten hatten seltsame Namen, Namen geändert
df = df.rename(columns={
    "Entity": "Land",
    "Code": "Kürzel",
    "Year": "Jahr",
    "civ_libs_vdem__estimate_best": "Index_Wert"
})

# Unnötige Spalte 'owid_region' noch entfernt
df = df.drop(columns=["owid_region"], errors="ignore")
df.head()

          Land Kürzel  Jahr  Index_Wert
0  Afghanistan    AFG  1789       0.121
1  Afghanistan    AFG  1790       0.121
2  Afghanistan    AFG  1791       0.121
3  Afghanistan    AFG  1792       0.121
4  Afghanistan    AFG  1793       0.121

- **Dies ist nun eine sinnvoll angepasste Tabelle für unser Projekt!**

### Format des Datensatz
- Welches Format hat mein Datensatz bzw. wie sind meine Kolumnen strukturiert?

- Welches Format kann ich für welche Teilschritte verwenden (wann soll ich pivot bzw. wide format verwenden)?

### Datentypen
- Welche Datentypen kommen in meinem Datensatz vor?

## 3. Statistik der Roh-Daten (Analyse im Long-Format)
- Ist meine Variable kontinuierlich oder diskret? Falls diskret, wieviele einzigartige Klassen gibt es? Wieviele Datenpunkte pro Klasse sind vorhanden?
- Anzahl Datenpunkte (Beschreibend und Graphische Darstellung)
    - Wieviele Datenpunkte sind für die bestimmten Variabeln vorhanden?
    - Wo fehlen Datenpunkte?
- Wie ist die Verteilung der zu untersuchenden Variabel(n) (Histogram, Boxplot, Säulendiagram)
- Vermutest du Zusammenhänge zwischen zwei Variabeln (Streuungsdiagramm, Korrelationsmatrix)

*Notiz: Zu jeder Kolumne sollte generell eine Aussage möglich sein.*

### 3.1 Roh-Daten-Analyse Gebiete

### 3.3 Roh-Daten-Analyse Jahr

## 4. Analyse
### Vorgehen
- Spezifische Untersuchung der Fragestellung (Berechnungen)
- Visualisieren der Resultate: Verwendet Achsenbeschriftung und überlegt euch, welche Art von Darstellung sinnvoll ist (Kuchen-, Säulen, Liniendiagramm; 2 y-Achsen?)
- Beschreiben der Beobachtungen
- Interpretation der Resultate (Hypothesen zu den Resultaten)
- Untermauern der Interpretation mittels Hinweise zur Literatur (Mögliche Zusammenhänge aufzeigen).
### Beobachtungen
### Interpretation
### Berechnungen
### Visualisierung